config/routes.rb
Rails.application.routes.draw do
  root :to => 'stories#index'
  
  resources :stories do
    resources :sentences
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, :presence => true
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  validates :author, :text, presence: true
  belongs_to :story
  validates :text, length: {minimum: 30, maximum: 200}
  before_save (:author_title_case)

private
  def author_title_case
    author = self.author.downcase
    words = author.split(' ')
    words.map do |word|
      word.capitalize!()
    end
    self.author = words.join(' ')
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, :author, :first_sentence, presence: true
  validates :first_sentence, length: {minimum: 30, maximum: 200}
  before_save(:title_case)
  before_save(:author_title_case)
  has_many :sentences

  private
    def title_case
      title = self.title.downcase
      words = title.split(' ')
      words.map do |word|
        word.capitalize!()
      end
      self.title = words.join(' ')
    end

    def author_title_case
      author = self.author.downcase
      words = author.split(' ')
      words.map do |word|
        word.capitalize!()
      end
      self.author = words.join(' ')
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def new
    @story = Story.find(params[:story_id])
    @sentence = @story.sentences.new
    @image = Image.order("RANDOM()").first
  end

  def create
    @image = Image.order("RANDOM()").first
    @story = Story.find(params[:story_id])
    @sentence = @story.sentences.new(sentence_params)
    if @sentence.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end


private
  def sentence_params
    params.require(:sentence).permit(:author, :text)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all.order(title: :asc)
  end

  def show
    @story = Story.find(params[:id])
    @sentences = @story.sentences
  end

  def new
    @story = Story.new
    @image = Image.order("RANDOM()").first
  end

  def create
    @image = Image.order("RANDOM()").first
    @story = Story.create(story_params)
    if @story.save
      redirect_to stories_path
    else
      render :new
    end
  end

  def update
    @story = Story.find(params[:id])

    if params[:favorite] == 'like'
      @story.favorites += 1
      @story.save
      redirect_to stories_path
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.sentences.each do |sentence|
      sentence.destroy
    end
    @story.destroy
    redirect_to stories_path
  end

private
  def story_params
    params.require(:story).permit(:title, :author, :first_sentence)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoryTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Sanchez' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic' rel='stylesheet' type='text/css'>
  <body>
  <nav class="navbar navbar-default navbar-fixed-bottom nav-pills">
    <div class="container-fluid">
      <div class="container">
        <ul class="nav navbar-nav">
          <li role="presentation"><%= link_to "Home", stories_path %></li>
          <%= yield(:link) %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="red-line">
    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/sentences/_form.html.erb
<%= render "layouts/errors", :object => @sentence %>

<div class ="form-container">
  <%= form_for [@story, @sentence], :html => {:class => "form-horizontal center"} do |f| %>
    <div class="form-group">
      <%= f.label :ftext, "Title", class: "control-label" %>
        <%= f.text_field :text, class: "form-control" %>
      </div>

    <div class="form-group">
      <%= f.label :fauthor, "Author", class: "control-label" %>
        <%= f.text_field :author, class: "form-control" %>
    </div>

    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>
</div>

app/views/sentences/new.html.erb
<h1>Add a sentence inspired by this image:</h1>

<div class="row">
  <%= image_tag ("#{@image.url}"), height: "300" %>
</div>

<div class="row">
  <%= @story.first_sentence %>
  <% @story.sentences.each do |sentence| %>
    <%= sentence.text %>
  <% end %>
</div>

<%= render 'form' %>

app/views/stories/_form.html.erb
<%= render "layouts/errors", :object => @story %>

<div class ="container">
  <%= form_for @story, :html => {:class => "form-horizontal center"} do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title", class: "control-label" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

    <div class="form-group">
      <%= f.label :author, "Author", class: "control-label" %>
        <%= f.text_field :author, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :first_sentence, "First Sentence", class: "control-label" %>
        <%= f.text_field :first_sentence, class: "form-control" %>
      </div>
    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>
</div>

app/views/stories/index.html.erb
<% content_for(:link) do %>

  <li role="presentation"><%= link_to 'Add a Story', new_story_path %></li>

<% end %>

<h1 class="main_head">Write Away</h1>

<% @stories.each do |story| %>
  <h3><%= link_to "#{story.title}", story_path(story) %></h3>
  <p><%= link_to '', story_path(story, :favorite => "like"), :method => "patch", class: "glyphicon glyphicon-heart-empty" %></span> <%= story.first_sentence %></p>
  <small><%= story.favorites %> Favorites</small>
<% end %>

app/views/stories/new.html.erb
<div class="container">
  <h1>Add a story inspired by this image:</h1>

  <%= image_tag ("#{@image.url}"), height: "300" %>

  <%= render 'form' %>
</div>

app/views/stories/show.html.erb
<% content_for(:link) do %>

  <li role="presentation" class="delete"><%= link_to "Delete #{@story.title}", story_path(@story), :method => "delete" %></li>

<% end %>

<h1 class="main_head"><%= @story.title %></h1>
<p><%= @story.author %>
<p><%= @story.first_sentence %></p>
<% @story.sentences.each do |sentence| %>
  <p><%= sentence.text %></p>
<% end %>

<%= link_to "Add the next sentence!", new_story_sentence_path(@story), class: "btn btn-warning" %>

<ul style="list-style: none">
  <li><h5>Contributors</h5></li>
  <li><%= @story.author %>
  <% @story.sentences.each do |sentence| %>
    <li><%= sentence.author %></li>
  <% end %>
</ul>